### ISSUE TITLE
Header Transition Broken

### ISSUE THREAD

**Issue by ramadanomar** [moinulmoin/chadnext#107]
https://github.com/moinulmoin/chadnext/assets/55840806/bf6c6ced-01e4-4106-9858-833a59213023

Can be fixed by removing the transition class. Thanks for this project! I've been using it to get inspiration on more clean coding practices w/ RSC & Next13 Server Actions! 

```tsx
<header
	className={cn(
		"sticky top-0 z-30  w-full bg-transparent ",
		scrolled ? " h-16 border-b backdrop-blur-xl" : " h-20"
	)}
>
```

**Comment by ramadanomar** [comment]
Or you can set scroll value to 0 which also fixes some other problems with it glitching like this
```tsx
const scrolled = useScroll(0);
```

**Comment by moinulmoin** [comment]
Thanks for pointing out!
