### ISSUE TITLE
How to solve the CORS issue in next 14 ?

### ISSUE THREAD

**Issue by zf0x00** [moinulmoin/chadnext#179]
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at [https://github.com/login/oauth/authorize?](https://github.com/login/oauth/authorize?response_type=code&client_id=123&state=7IC-dQ_H30x4TPuJ-BKYK-tapVSKKvVA)`

i tried many ways but cant solve the issue

**Comment by moinulmoin** [comment]
can you please share the reproducing steps for this?? Thanks
