### ISSUE TITLE
User subscription information does not update in database

### ISSUE THREAD

**Issue by graham-fleming** [moinulmoin/chadnext#182]
When a user upgrades to a pro account, the Stripe session appears to be successful and the subscription is created.

But the information in the database does not update, only the "Updated at" and the other fields are blank. 

```
Stripe current period end
-
Stripe customer id
-
Stripe price id
-
Stripe subscription id
-
Updated at
02/08/2024 7:10:16 PM
```

Is this a known problem?

**Comment by moinulmoin** [comment]
yes, will fix it for sure, some redirecting is causing this

**Comment by graham-fleming** [comment]
Is there a fix?

With Vercel the default domain setup included the "www" redirecting everything to it

Should the domain for NEXT_PUBLIC_APP_URL and stripe webhook url include the "www"?

Where should I look to check for errors?

HTTP status code 308 (Permanent Redirect)

<img width="731" alt="image" src="https://github.com/moinulmoin/chadnext/assets/46798655/4f196a2f-6bd2-4755-b912-ef55d510302d">

**Comment by graham-fleming** [comment]
Adding a trailing slash to the Stripe webhook URL in the stripe dashboard fixed the problem

**Comment by moinulmoin** [comment]
Genius, Let me check!

**Comment by moinulmoin** [comment]
thanks, it is solved now.

**Comment by graham-fleming** [comment]
Great! good to hear. Possibly related to the trailingSlash: true in next.config.js

**Comment by mikeXdev** [comment]
> Adding a trailing slash to the Stripe webhook URL in the stripe dashboard fixed the problem

May I know how did you fix this? I don't have webhook url setup on my end.
