### ISSUE TITLE
[next-international] run time error

### ISSUE THREAD

**Issue by noteclub9** [moinulmoin/chadnext#226]
Although the server is running smoothly, an error is consistently logged in the terminal upon each refresh.

`[next-international] The locale 'cart.json' is not supported. Defined locales are: [en, fr].`

![image](https://github.com/moinulmoin/chadnext/assets/166605044/88c7bf99-0dfb-470d-a0f5-40fff6c1569e)

**Comment by moinulmoin** [comment]
if I understand correctly, you put `cart.json` which is not acceptable for the default locale, check here how to setup the locale

https://next-international.vercel.app/docs/app-setup
