### ISSUE TITLE
Google auth integration: record does not get added to the prisma table

### ISSUE THREAD

**Issue by chiragksharma** [moinulmoin/chadnext#228]
I have used vercel postgress prisma table for storing the records with the google id and github id.
and set the redirect uri to this:
 `"http:localhost:3000/en/dashboard/projects/"`
But as soon as authenticate via google it redirects me again to the login page.
I am not able to access the dashboard page even after authenticating.
Same happens with the github authentication

**Comment by moinulmoin** [comment]
I don't know what's going on there, if you could show how to reproduce the issue, it would be helpful, otherwise, you can check the multiple oauth / google oauth implementation docs in lucia auth

https://arctic.js.org/providers/google
https://lucia-auth.com/guides/oauth/
