### ISSUE TITLE
Safety Issue

### ISSUE THREAD

**Issue by ashadnasim52** [moinulmoin/chadnext#246]
Why is this script collecting data?

  {process.env.NODE_ENV === "production" && (
        <Script
          src="https://umami.moinulmoin.com/script.js"
          data-website-id="bc66d96a-fc75-4ecd-b0ef-fdd25de8113c"
        />
      )}

**Comment by moinulmoin** [comment]
Hey, that was collecting the usage of chadnext. You can remove this in your app/fork or use your analytics.
