### ISSUE TITLE
Dashboard settings QOL

### ISSUE THREAD

**Issue by zahid47** [moinulmoin/chadnext#49]
Hey, I was messing around with the dashboard settings and found a few things that could be improved.

1. If you upload a horizontal profile picture it looks compressed.
2. If you try to upload an invalid image (filename has space) it doesn't show any error.
3. Short bio is initially blank, so it should be an optional field. Right now, If you try to change my profile picture or name, you are also forced to add a short bio.
4. If you try to leave a dirty form, there should be a confirmation dialog.

I would like to open a PR to address these.

Though I'm not sure how to deal with number 4. I did some research and there's this window event called `beforeunload` but it doesn't seem to trigger for next router.  And the new Next 13 router doesn't support events yet (maybe it will be possible after they add router events?)

What do you think?

**Comment by moinulmoin** [comment]
Thanks for addressing these issues. I checked and I think we can skip 1, 2 and you can work on 3rd now and 4th when router events will be supported in App router.
