### ISSUE TITLE
Can not even run

### ISSUE THREAD

**Issue by luohao123** [moinulmoin/chadnext#71]
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! node:internal/modules/cjs/loader:942
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'streamx'
npm ERR! Require stack:

**Comment by moinulmoin** [comment]
Hey, I have checked just now and everything working fine. Can you tell me how to reproduce this?

**Comment by luohao123** [comment]
hello, using pnpm got it work!

thanks for this helpful template!


btw, I found after I set these github id and scerete and callback url, I click the loigin with github button ,it won't jump to github , do u know why

**Comment by moinulmoin** [comment]
did you setup github oauth app correctly and github credentials?

**Comment by luohao123** [comment]
yes, using localhost for testing, the id and apikey are set in `.env`, but click register with gjithub, no response

**Comment by moinulmoin** [comment]
Sorry, I couldn't help you much. Did you solve that issue?
